CREATE TABLE IF NOT EXISTS PROJECTS
(
    ID          SERIAL       NOT NULL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION TEXT         NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID         SERIAL       NOT NULL PRIMARY KEY,
    FIRSTNAME  VARCHAR(255) NOT NULL,
    LASTNAME   VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) UNIQUE,
    PROJECT_ID INTEGER,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS TASKS
(
    ID           SERIAL       NOT NULL PRIMARY KEY,
    TITLE        VARCHAR(255) NOT NULL,
    DESCRIPTION  TEXT         NOT NULL,
    CREATED_DATE TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DUE_DATE     TIMESTAMPTZ  NOT NULL,
    STATUS       VARCHAR      NOT NULL,
    ASSIGNEE_ID  INTEGER      REFERENCES USERS (ID) ON DELETE SET NULL,
    PROJECT_ID   INTEGER REFERENCES PROJECTS (ID) ON DELETE CASCADE
);