CREATE TABLE IF NOT EXISTS USERS
(
    ID        SERIAL       NOT NULL PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME  VARCHAR(255) NOT NULL,
    EMAIL     VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS TASKS
(
    ID           SERIAL       NOT NULL PRIMARY KEY,
    TITLE        VARCHAR(255) NOT NULL,
    DESCRIPTION  TEXT         NOT NULL,
    CREATED_DATE TIMESTAMPTZ  NOT NULL,
    DUE_DATE     TIMESTAMPTZ  NOT NULL,
    STATUS       VARCHAR      NOT NULL,
    ASSIGNEE_ID  INTEGER REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS PROJECTS
(
    ID          SERIAL       NOT NULL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT         NOT NULL,
    CREATOR_ID  INTEGER REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS PROJECT_TASKS
(
    PROJECT_ID INTEGER NOT NULL REFERENCES PROJECTS(ID),
    TASK_ID    INTEGER NOT NULL REFERENCES TASKS(ID),
    PRIMARY KEY (PROJECT_ID,TASK_ID)
);

CREATE TABLE IF NOT EXISTS USERS_PROJECTS
(
    USER_ID    INTEGER NOT NULL REFERENCES USERS(ID),
    PROJECT_ID INTEGER NOT NULL REFERENCES PROJECTS(ID),
    PRIMARY KEY (USER_ID,PROJECT_ID)
);