INSERT INTO USERS (FIRSTNAME, LASTNAME, EMAIL)
VALUES ('vitya', 'sinkevich', 'vitya2@gmail.com');

INSERT INTO TASKS (TITLE, DESCRIPTION, CREATED_DATE, DUE_DATE, STATUS, ASSIGNEE_ID)
VALUES ('create', 'create db', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'IN PROGRESS', 1);

INSERT INTO PROJECTS (NAME, DESCRIPTION, CREATOR_ID)
VALUES ('APP', 'PROJECT', 3);

INSERT INTO USERS_PROJECTS (USER_ID, PROJECT_ID)
VALUES (1, 2);

INSERT INTO USERS_PROJECTS (USER_ID, PROJECT_ID)
VALUES (3, 2);